// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/categories": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Récupère la liste de toutes les catégories (admin uniquement)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Categories"
                ],
                "summary": "Liste toutes les catégories",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dtos.CategoryResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Accès refusé - Admin requis",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Crée une nouvelle catégorie (admin uniquement)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Categories"
                ],
                "summary": "Créer une catégorie",
                "parameters": [
                    {
                        "description": "Informations de la catégorie",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.CategoryRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dtos.CategoryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Accès refusé - Admin requis",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Catégorie avec ce nom existe déjà",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/categories/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Récupère les détails d'une catégorie par son ID (admin uniquement)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Categories"
                ],
                "summary": "Détails d'une catégorie",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de la catégorie",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.CategoryResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Accès refusé - Admin requis",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Met à jour une catégorie existante (admin uniquement)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Categories"
                ],
                "summary": "Mettre à jour une catégorie",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de la catégorie",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Nouvelles informations de la catégorie",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.CategoryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.CategoryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Accès refusé - Admin requis",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Supprime une catégorie (admin uniquement)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Categories"
                ],
                "summary": "Supprimer une catégorie",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de la catégorie",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Accès refusé - Admin requis",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Met à jour uniquement le nom d'une catégorie (admin uniquement). Exemple: changer uniquement le nom sans recréer la catégorie.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Categories"
                ],
                "summary": "Mettre à jour partiellement une catégorie",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de la catégorie",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Champs à mettre à jour (nom optionnel)",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.PatchCategoryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.CategoryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Accès refusé - Admin requis",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/orders": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Récupère toutes les commandes de tous les utilisateurs (admin uniquement)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orders"
                ],
                "summary": "Liste toutes les commandes",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dtos.OrderResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Accès refusé - Admin requis",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/orders/{id}/status": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Met à jour le statut d'une commande (PENDING, SHIPPED, DELIVERED, CANCELLED) - admin uniquement",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orders"
                ],
                "summary": "Mettre à jour le statut d'une commande",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de la commande",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Nouveau statut",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.UpdateOrderStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.OrderResponse"
                        }
                    },
                    "400": {
                        "description": "Statut invalide",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Accès refusé - Admin requis",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/products": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Crée un nouveau produit (admin uniquement)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Products"
                ],
                "summary": "Créer un produit",
                "parameters": [
                    {
                        "description": "Informations du produit",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.ProductRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dtos.ProductResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Accès refusé - Admin requis",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Produit avec ce nom existe déjà",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/products/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Met à jour un produit existant (admin uniquement)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Products"
                ],
                "summary": "Mettre à jour un produit",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID du produit",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Nouvelles informations du produit",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.ProductRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.ProductResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Accès refusé - Admin requis",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Supprime un produit (admin uniquement)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Products"
                ],
                "summary": "Supprimer un produit",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID du produit",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Accès refusé - Admin requis",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Met à jour uniquement les champs fournis d'un produit (admin uniquement). Exemple: changer uniquement l'image sans modifier les autres champs.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Products"
                ],
                "summary": "Mettre à jour partiellement un produit",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID du produit",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Champs à mettre à jour (tous optionnels)",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.PatchProductRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.ProductResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Accès refusé - Admin requis",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/user/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Supprime un utilisateur par son ID. Réservé aux administrateurs.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Supprimer un utilisateur (Admin uniquement)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de l'utilisateur",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/users": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Récupère la liste de tous les utilisateurs. Réservé aux administrateurs.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Liste tous les utilisateurs (Admin uniquement)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dtos.UserResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Authentifie un utilisateur et retourne un token JWT",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Connexion utilisateur",
                "parameters": [
                    {
                        "description": "Identifiants de connexion",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Email ou mot de passe incorrect",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Récupère les informations de l'utilisateur connecté via le token JWT",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Informations utilisateur actuel",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.UserResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Crée un nouveau compte utilisateur et retourne un token JWT",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Inscription d'un nouvel utilisateur",
                "parameters": [
                    {
                        "description": "Informations d'inscription",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.UserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dtos.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Email déjà utilisé",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/orders": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Récupère toutes les commandes de l'utilisateur connecté",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orders"
                ],
                "summary": "Liste les commandes de l'utilisateur",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dtos.OrderResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Crée une nouvelle commande avec les produits sélectionnés. Le stock est automatiquement déduit.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orders"
                ],
                "summary": "Créer une commande",
                "parameters": [
                    {
                        "description": "Items de la commande",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.CreateOrderRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dtos.OrderResponse"
                        }
                    },
                    "400": {
                        "description": "Stock insuffisant ou produit non trouvé",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/orders/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Récupère les détails d'une commande. L'utilisateur peut voir ses propres commandes, l'admin peut voir toutes les commandes.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orders"
                ],
                "summary": "Détails d'une commande",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de la commande",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.OrderResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/products": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Récupère la liste de tous les produits disponibles avec leurs catégories (authentification requise). Supporte la pagination via ?page=1\u0026limit=10",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Products"
                ],
                "summary": "Liste tous les produits",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Numéro de page (défaut: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Nombre d'éléments par page (défaut: 10, max: 100)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Si page et limit ne sont pas fournis",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dtos.ProductResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/products/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Récupère les détails d'un produit par son ID (authentification requise)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Products"
                ],
                "summary": "Détails d'un produit",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID du produit",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.ProductResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/products/{productID}/reviews": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Récupère tous les avis d'un produit avec statistiques (moyenne, total)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reviews"
                ],
                "summary": "Liste des avis d'un produit",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID du produit",
                        "name": "productID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.ProductReviewsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Permet à un utilisateur authentifié de laisser un avis (note et commentaire) sur un produit",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reviews"
                ],
                "summary": "Créer un avis pour un produit",
                "parameters": [
                    {
                        "description": "Données de l'avis",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.CreateReviewRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dtos.ReviewResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/products/{productID}/reviews/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Récupère l'avis de l'utilisateur connecté pour un produit spécifique",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reviews"
                ],
                "summary": "Avis de l'utilisateur pour un produit",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID du produit",
                        "name": "productID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.ReviewResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Aucun avis trouvé"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/reviews/{reviewID}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Permet à un utilisateur de modifier son propre avis",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reviews"
                ],
                "summary": "Mettre à jour un avis",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de l'avis",
                        "name": "reviewID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Données de mise à jour",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.UpdateReviewRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.ReviewResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Permet à un utilisateur de supprimer son propre avis",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reviews"
                ],
                "summary": "Supprimer un avis",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de l'avis",
                        "name": "reviewID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/docs.SuccessMessage"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/user/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Récupère les informations d'un utilisateur par son ID. L'utilisateur peut voir son propre profil, l'admin peut voir n'importe quel profil.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Récupérer un utilisateur",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de l'utilisateur",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.UserResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Met à jour les informations d'un utilisateur. L'utilisateur peut modifier son propre profil, l'admin peut modifier n'importe quel profil.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Mettre à jour un utilisateur",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de l'utilisateur",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Nouvelles informations",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.UserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dtos.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users": {
            "post": {
                "description": "Crée un nouvel utilisateur (sans authentification requise)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Créer un utilisateur",
                "parameters": [
                    {
                        "description": "Informations utilisateur",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.UserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/dtos.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Email déjà utilisé",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "docs.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Message d'erreur"
                }
            }
        },
        "docs.SuccessMessage": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Opération réussie"
                }
            }
        },
        "dtos.CategoryRequest": {
            "description": "Informations catégorie pour création/modification",
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "description": "Nom de la catégorie",
                    "type": "string",
                    "example": "Visage"
                }
            }
        },
        "dtos.CategoryResponse": {
            "description": "Informations catégorie",
            "type": "object",
            "properties": {
                "createdAt": {
                    "description": "Date de création",
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "id": {
                    "description": "UUID de la catégorie",
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "name": {
                    "description": "Nom de la catégorie",
                    "type": "string",
                    "example": "Visage"
                },
                "updatedAt": {
                    "description": "Date de mise à jour",
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                }
            }
        },
        "dtos.CreateOrderRequest": {
            "description": "Requête de création de commande",
            "type": "object",
            "required": [
                "items"
            ],
            "properties": {
                "items": {
                    "description": "Liste des items de la commande (minimum 1)",
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/dtos.OrderItemRequest"
                    }
                }
            }
        },
        "dtos.CreateReviewRequest": {
            "description": "Avis utilisateur sur un produit",
            "type": "object",
            "required": [
                "productID",
                "rating"
            ],
            "properties": {
                "comment": {
                    "description": "Commentaire (optionnel)",
                    "type": "string",
                    "example": "Excellent produit, très satisfait !"
                },
                "productID": {
                    "description": "ID du produit",
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "rating": {
                    "description": "Note de 1 à 5 (obligatoire)",
                    "type": "integer",
                    "maximum": 5,
                    "minimum": 1,
                    "example": 5
                }
            }
        },
        "dtos.LoginRequest": {
            "description": "Identifiants de connexion",
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "description": "Email de l'utilisateur",
                    "type": "string",
                    "example": "user@example.com"
                },
                "password": {
                    "description": "Mot de passe",
                    "type": "string",
                    "example": "password123"
                }
            }
        },
        "dtos.LoginResponse": {
            "description": "Réponse de connexion avec token JWT",
            "type": "object",
            "properties": {
                "token": {
                    "description": "Token JWT",
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                },
                "user": {
                    "description": "Informations de l'utilisateur",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dtos.UserResponse"
                        }
                    ]
                }
            }
        },
        "dtos.OrderItemRequest": {
            "description": "Item de commande avec produit et quantité",
            "type": "object",
            "required": [
                "productID",
                "quantity"
            ],
            "properties": {
                "productID": {
                    "description": "ID du produit",
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "quantity": {
                    "description": "Quantité commandée (doit être \u003e 0)",
                    "type": "integer",
                    "example": 2
                }
            }
        },
        "dtos.OrderItemResponse": {
            "description": "Item de commande avec détails du produit",
            "type": "object",
            "properties": {
                "id": {
                    "description": "UUID de l'item",
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "price": {
                    "description": "Prix unitaire au moment de la commande",
                    "type": "number",
                    "example": 29.99
                },
                "product": {
                    "description": "Détails du produit",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dtos.ProductResponse"
                        }
                    ]
                },
                "quantity": {
                    "description": "Quantité commandée",
                    "type": "integer",
                    "example": 2
                }
            }
        },
        "dtos.OrderResponse": {
            "description": "Informations complètes d'une commande",
            "type": "object",
            "properties": {
                "createdAt": {
                    "description": "Date de création",
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "id": {
                    "description": "UUID de la commande",
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "orderDate": {
                    "description": "Date de la commande",
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "orderItems": {
                    "description": "Liste des items de la commande",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.OrderItemResponse"
                    }
                },
                "status": {
                    "description": "Statut de la commande",
                    "type": "string",
                    "enum": [
                        "PENDING",
                        "SHIPPED",
                        "DELIVERED",
                        "CANCELLED"
                    ],
                    "example": "PENDING"
                },
                "totalAmount": {
                    "description": "Montant total de la commande",
                    "type": "number",
                    "example": 59.98
                },
                "updatedAt": {
                    "description": "Date de mise à jour",
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "userID": {
                    "description": "ID de l'utilisateur",
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "dtos.PaginatedProductsResponse": {
            "type": "object",
            "properties": {
                "hasNext": {
                    "description": "Y a-t-il une page suivante ?",
                    "type": "boolean"
                },
                "hasPrev": {
                    "description": "Y a-t-il une page précédente ?",
                    "type": "boolean"
                },
                "limit": {
                    "description": "Nombre d'éléments par page",
                    "type": "integer"
                },
                "page": {
                    "description": "Page actuelle",
                    "type": "integer"
                },
                "products": {
                    "description": "Liste des produits",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.ProductResponse"
                    }
                },
                "total": {
                    "description": "Nombre total de produits",
                    "type": "integer"
                },
                "totalPages": {
                    "description": "Nombre total de pages",
                    "type": "integer"
                }
            }
        },
        "dtos.PatchCategoryRequest": {
            "description": "Permet de mettre à jour uniquement le nom d'une catégorie",
            "type": "object",
            "properties": {
                "name": {
                    "description": "Nom de la catégorie (optionnel)",
                    "type": "string",
                    "example": "Visage"
                }
            }
        },
        "dtos.PatchProductRequest": {
            "description": "Permet de mettre à jour uniquement certains champs d'un produit (tous les champs sont optionnels)",
            "type": "object",
            "properties": {
                "categoryID": {
                    "description": "ID de la catégorie (optionnel, peut être null pour supprimer la catégorie)",
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "description": {
                    "description": "Description du produit (optionnel)",
                    "type": "string",
                    "example": "Crème hydratante pour peau sensible"
                },
                "imageURL": {
                    "description": "URL de l'image du produit (optionnel)",
                    "type": "string",
                    "example": "https://example.com/image.jpg"
                },
                "name": {
                    "description": "Nom du produit (optionnel)",
                    "type": "string",
                    "example": "Crème hydratante"
                },
                "price": {
                    "description": "Prix en euros (optionnel, doit être \u003e 0 si fourni)",
                    "type": "number",
                    "example": 29.99
                },
                "stock": {
                    "description": "Quantité en stock (optionnel, doit être \u003e= 0 si fourni)",
                    "type": "integer",
                    "example": 50
                }
            }
        },
        "dtos.ProductRequest": {
            "description": "Informations produit pour création/modification",
            "type": "object",
            "required": [
                "name",
                "price"
            ],
            "properties": {
                "categoryID": {
                    "description": "ID de la catégorie (optionnel)",
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "description": {
                    "description": "Description du produit",
                    "type": "string",
                    "example": "Crème hydratante pour peau sensible"
                },
                "imageURL": {
                    "description": "URL de l'image du produit",
                    "type": "string",
                    "example": "https://example.com/image.jpg"
                },
                "name": {
                    "description": "Nom du produit",
                    "type": "string",
                    "example": "Crème hydratante"
                },
                "price": {
                    "description": "Prix en euros (doit être \u003e 0)",
                    "type": "number",
                    "example": 29.99
                },
                "stock": {
                    "description": "Quantité en stock",
                    "type": "integer",
                    "minimum": 0,
                    "example": 50
                }
            }
        },
        "dtos.ProductResponse": {
            "description": "Informations produit avec catégorie",
            "type": "object",
            "properties": {
                "category": {
                    "description": "Informations de la catégorie (si disponible)",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dtos.CategoryResponse"
                        }
                    ]
                },
                "categoryID": {
                    "description": "ID de la catégorie",
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "createdAt": {
                    "description": "Date de création",
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "description": {
                    "description": "Description",
                    "type": "string",
                    "example": "Crème hydratante pour peau sensible"
                },
                "id": {
                    "description": "UUID du produit",
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "imageURL": {
                    "description": "URL de l'image",
                    "type": "string",
                    "example": "https://example.com/image.jpg"
                },
                "name": {
                    "description": "Nom du produit",
                    "type": "string",
                    "example": "Crème hydratante"
                },
                "price": {
                    "description": "Prix en euros",
                    "type": "number",
                    "example": 29.99
                },
                "stock": {
                    "description": "Quantité en stock",
                    "type": "integer",
                    "example": 50
                },
                "updatedAt": {
                    "description": "Date de mise à jour",
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                }
            }
        },
        "dtos.ProductReviewsResponse": {
            "description": "Liste des avis avec statistiques (moyenne, total)",
            "type": "object",
            "properties": {
                "averageRating": {
                    "description": "Note moyenne (0-5)",
                    "type": "number",
                    "example": 4.5
                },
                "reviews": {
                    "description": "Liste des avis",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtos.ReviewResponse"
                    }
                },
                "totalReviews": {
                    "description": "Nombre total d'avis",
                    "type": "integer",
                    "example": 10
                }
            }
        },
        "dtos.ReviewResponse": {
            "description": "Informations complètes d'un avis",
            "type": "object",
            "properties": {
                "comment": {
                    "description": "Commentaire (optionnel)",
                    "type": "string",
                    "example": "Excellent produit !"
                },
                "createdAt": {
                    "description": "Date de création",
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "id": {
                    "description": "UUID de l'avis",
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "productID": {
                    "description": "ID du produit",
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "rating": {
                    "description": "Note de 1 à 5",
                    "type": "integer",
                    "example": 5
                },
                "updatedAt": {
                    "description": "Date de mise à jour",
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "userEmail": {
                    "description": "Email de l'utilisateur (pour affichage)",
                    "type": "string",
                    "example": "user@example.com"
                },
                "userID": {
                    "description": "ID de l'utilisateur",
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "dtos.UpdateOrderStatusRequest": {
            "description": "Nouveau statut de commande",
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "status": {
                    "description": "Nouveau statut",
                    "type": "string",
                    "enum": [
                        "PENDING",
                        "SHIPPED",
                        "DELIVERED",
                        "CANCELLED"
                    ],
                    "example": "SHIPPED"
                }
            }
        },
        "dtos.UpdateReviewRequest": {
            "description": "Mise à jour d'un avis existant",
            "type": "object",
            "properties": {
                "comment": {
                    "description": "Commentaire (optionnel)",
                    "type": "string",
                    "example": "Bon produit mais pourrait être meilleur"
                },
                "rating": {
                    "description": "Note de 1 à 5 (optionnel)",
                    "type": "integer",
                    "maximum": 5,
                    "minimum": 1,
                    "example": 4
                }
            }
        },
        "dtos.UserRequest": {
            "description": "Informations utilisateur pour inscription/modification",
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "description": "Email de l'utilisateur",
                    "type": "string",
                    "example": "user@example.com"
                },
                "password": {
                    "description": "Mot de passe (min 6 caractères)",
                    "type": "string",
                    "minLength": 6,
                    "example": "password123"
                }
            }
        },
        "dtos.UserResponse": {
            "description": "Informations utilisateur (sans mot de passe)",
            "type": "object",
            "properties": {
                "createdAt": {
                    "description": "Date de création",
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                },
                "email": {
                    "description": "Email de l'utilisateur",
                    "type": "string",
                    "example": "user@example.com"
                },
                "id": {
                    "description": "UUID de l'utilisateur",
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "role": {
                    "description": "Rôle: USER ou ADMIN",
                    "type": "string",
                    "enum": [
                        "USER",
                        "ADMIN"
                    ],
                    "example": "USER"
                },
                "updatedAt": {
                    "description": "Date de mise à jour",
                    "type": "string",
                    "example": "2024-01-01T00:00:00Z"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" suivi d'un espace et du token JWT. Exemple: \"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "PORELO Skincare Shop API",
	Description:      "API REST complète pour une boutique de produits de soins (skincare shop) avec authentification JWT et gestion des rôles.\nCette API permet de gérer les produits, catégories, commandes et utilisateurs.\n\n## Authentification\nLa plupart des endpoints nécessitent une authentification JWT. Pour tester les endpoints protégés :\n\n**Étape 1 : Obtenir un token**\n1. Utilisez `/auth/register` pour créer un compte OU `/auth/login` pour vous connecter\n2. Copiez le token JWT retourné dans la réponse (champ \"token\")\n\n**Étape 2 : Autoriser les requêtes dans Swagger UI**\n1. Cliquez sur le bouton **\"Authorize\"** (icône de cadenas) en haut à droite de cette page\n2. Dans le champ \"Value\", entrez : `Bearer <votre-token>` (remplacez `<votre-token>` par le token copié)\n3. Cliquez sur **\"Authorize\"** puis **\"Close\"**\n\n**Étape 3 : Tester les endpoints**\nTous les endpoints protégés sont maintenant accessibles. Vous pouvez cliquer sur \"Try it out\" et tester chaque endpoint.\n\n## Rôles\n- **USER** : Peut voir les produits, créer des commandes, voir ses propres commandes\n- **ADMIN** : Accès complet à toutes les ressources\n\n---\n\n## 🔐 Compte de test Admin\n\n**Email:** `momo@ynov.com`\n**Password:** `Password2025`\n\nUtilisez ce compte pour tester toutes les fonctionnalités admin dans l'API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
